icap_server:
  address: "0.0.0.0"
  port: 1344
  restricted_classes:
    - alt.atheism
    - soc.religion.christian
    - sci.med
  classifier_status:
    bayes: False
    svm: False
    cnn: True
  content_min_length: 50
  replacement_http_method: POST
  replacement_url: http://opentc.example.com/classifier/request_submit/
  converter:
    "text/plain": text
    "message/rfc822": text
    "application/x-www-form-urlencoded": text
    "application/msword": textract
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": textract
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": textract
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": textract
    "application/epub+zip": textract
    "application/json": textract
    "application/pdf": textract
    "application/postscript": textract
    "application/rtf": textract
    "application/excel": textract
    "image/tiff": textract
    "text/html": textract
    "text/csv": textract

opentc_server:
  address: localhost
  port: 3333
